name: /dev/lawyer
description: law, technology, and the space between
url: https://writing.kemitchell.com
permalink: :year/:month/:day/:title.html
author: Kyle E. Mitchell
homepage: https://kemitchell.com
highlighter: rouge
excerpt_separator: "<!--jump-->"
repository: kemitchell/writing
repository_url: "https://github.com/kemitchell/writing"
plugins:
- jekyll-sass-converter
- jekyll-feed
exclude:
- vendor
defaults:
  - scope:
      path: ""
      type: posts
    values:
      is_post: true
